# Tensorflow:

In [6]:
import tensorflow as tf

print("The tensorflow version is:", tf.__version__)

The tensorflow version is: 1.10.0


## Constants:

In [8]:
hello = tf.constant("Hello")
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [9]:
world = tf.constant("World")
print(world)

Tensor("Const_1:0", shape=(), dtype=string)


In [10]:
world = tf.constant("World")
print(world)

Tensor("Const_2:0", shape=(), dtype=string)


In [11]:
world = tf.constant("World")
print(world)

Tensor("Const_3:0", shape=(), dtype=string)


In [12]:
type(hello)

tensorflow.python.framework.ops.Tensor

## Sessions:

In [13]:
with tf.Session() as sess:
    result = sess.run(hello + world)

print(result)

b'HelloWorld'


In [14]:
#how to add two numbers

num1 = tf.constant(10)
num2 = tf.constant(100)

with tf.Session() as sess:
    s = sess.run(num1 + num2)
    
print("The sum is:", s)

The sum is: 110


In [31]:
tens = tf.fill((5,5),10)
zeros = tf.zeros((5,5))
ones = tf.ones((5,5))
randn = tf.random_normal((5,5), mean=0, stddev=1.0)
randu = tf.random_uniform((5,5), minval=0, maxval=1)

In [32]:
const = tf.constant(5)

In [33]:
mymethod = [const, tens, zeros, ones, randn, randu]

In [35]:
sess = tf.InteractiveSession()

In [36]:
for my in mymethod:
    print(sess.run(my))
    print('\n')

5


[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


[[ 0.28026545  1.3190225  -1.881624    1.4006066  -0.0076632 ]
 [ 0.78485364 -2.5427542  -0.10941369  1.3294429  -0.4528029 ]
 [-0.03640976  1.7344714   0.97714114  1.1068205   0.1333591 ]
 [-0.2927276   0.74203974  1.2883278   0.74311435 -0.8726402 ]
 [-1.5407395   1.0859035   0.4924888   1.0646701  -0.6478197 ]]


[[0.8725685  0.8268715  0.04930127 0.6555995  0.84688854]
 [0.22049308 0.5396702  0.141312   0.8203578  0.74491715]
 [0.8352256  0.53348553 0.49205422 0.68526745 0.082057  ]
 [0.298159   0.29055965 0.9223418  0.70084536 0.89978445]
 [0.66983724 0.2597674  0.2425543  0.33793867 0.30817235]]




In [37]:
#Second method for session: eval
for i in mymethod:
    print(i.eval())
    print("\n")

5


[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


[[-0.254683   -0.5914323   0.23242639  1.7363476   0.3617251 ]
 [ 1.0948666  -0.14655755 -0.83523935 -1.2740047  -1.2690029 ]
 [ 1.0139107  -0.7013162   1.4701296  -0.14826822 -0.76736444]
 [-0.03463251 -0.20103487 -1.4728683   1.4477028  -1.5270038 ]
 [ 0.846078   -1.0645773   0.5053752   0.13128042  0.19709049]]


[[0.89547384 0.04278135 0.6458281  0.6768575  0.8889556 ]
 [0.7232603  0.00105941 0.4631791  0.77465737 0.3971492 ]
 [0.472939   0.557377   0.9460995  0.94239223 0.4507606 ]
 [0.7970457  0.29005313 0.30916345 0.7362566  0.7588346 ]
 [0.7807319  0.25290596 0.25314248 0.6845176  0.16715646]]




In [42]:
#Finding shape
a = tf.fill((5,5),6)

In [43]:
a.get_shape()

TensorShape([Dimension(5), Dimension(5)])

In [44]:
mult = tf.matmul(a, tens)

In [45]:
print(sess.run(mult))

[[300 300 300 300 300]
 [300 300 300 300 300]
 [300 300 300 300 300]
 [300 300 300 300 300]
 [300 300 300 300 300]]


In [46]:
print(mult.eval())

[[300 300 300 300 300]
 [300 300 300 300 300]
 [300 300 300 300 300]
 [300 300 300 300 300]
 [300 300 300 300 300]]


## Graph:

In [47]:
#Creating or generating graph

num3 = num1 + num2

In [48]:
with tf.Session() as sess:
    print(sess.run(num3))

110


In [49]:
#Default graph
print(tf.get_default_graph())

In [50]:
#Creating own graphs
g = tf.Graph()

In [51]:
g1 = tf.Graph()
print(g1)

In [52]:
g2 = tf.Graph()
print(g2)

In [53]:
#Setting a graph as default

with g2.as_default():
    print("Inside session.")
    print(g2 is tf.get_default_graph())
    
print("Outside session.")
print(g2 is tf.get_default_graph())

Inside session.
True
Outside session.
False


## Variables:

In [54]:
import tensorflow as tf

print("The tensorflow version is:", tf.__version__)

The tensorflow version is: 1.10.0


In [56]:
sess = tf.InteractiveSession()

In [57]:
my_tensor = tf.random_uniform((5,5),0,2)

In [58]:
var1 = tf.Variable(initial_value=my_tensor)

In [62]:
init = tf.global_variables_initializer()

In [63]:
sess.run(init)

In [64]:
sess.run(var1)

array([[1.7190535 , 0.34114432, 0.66239214, 1.1468911 , 1.009295  ],
       [1.2546208 , 0.45872808, 1.9645753 , 0.10663986, 0.25311232],
       [0.5602772 , 1.6995099 , 0.76995206, 0.80440736, 1.5129762 ],
       [1.6334476 , 0.9260309 , 0.3273542 , 0.3041811 , 0.7465265 ],
       [0.9435401 , 0.9345944 , 0.15495157, 1.4810691 , 0.7597301 ]],
      dtype=float32)

## Placeholder:

In [66]:
ph1 = tf.placeholder(tf.float32, shape=(4,4))
ph1

<tf.Tensor 'Placeholder:0' shape=(4, 4) dtype=float32>