In [2]:
import tensorflow as tf

In [3]:
import numpy as np

In [4]:
#Collecting sample

np.random.seed(101)
tf.set_random_seed(101)

In [5]:
rand_a = np.random.uniform(0,100,(5,5))

print(rand_a)

[[51.63986277 57.06675869  2.84742265 17.15216562 68.52769817]
 [83.38968626 30.69662197 89.36130797 72.15438618 18.99389542]
 [55.42275911 35.2131954  18.18924027 78.56017619 96.54832224]
 [23.23536618  8.35614337 60.35484223 72.89927573 27.62388285]
 [68.53063288 51.78674742  4.84845374 13.78692376 18.69674261]]


In [7]:
rand_b = np.random.uniform(0,100,(5,1))
print(rand_b)

[[91.31535577]
 [80.7920151 ]
 [40.29978307]
 [35.72243428]
 [95.28767147]]


In [8]:
#Creating placeholder

a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

In [9]:
#Performing two operations

add = a + b
mul = a * b

In [11]:
#Creating session and pass data to placeholder with feed dict

with tf.Session() as sess:
    add_result = sess.run(add, feed_dict={a:rand_a, b:rand_b})
    print(add_result)
    print('\n')
    
    mul_result = sess.run(mul, feed_dict={a:rand_a, b:rand_b})
    print(mul_result)

[[142.95522  148.38211   94.16277  108.46752  159.84305 ]
 [164.1817   111.48864  170.15332  152.94641   99.78591 ]
 [ 95.72254   75.51298   58.48902  118.859955 136.84811 ]
 [ 58.9578    44.07858   96.07728  108.62171   63.346317]
 [163.8183   147.07442  100.13612  109.0746   113.98442 ]]


[[4715.512   5211.0713   260.0134  1566.2561  6257.631  ]
 [6737.2207  2480.042   7219.6797  5829.4985  1534.555  ]
 [2233.5251  1419.0841   733.0224  3165.9578  3890.8765 ]
 [ 830.02386  298.50177 2156.022   2604.1396   986.79236]
 [6530.1245  4934.6387   461.99786 1313.7239  1781.5691 ]]
